services:
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector
    environment:
      POSTGRES_DB: ai
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai -d ai"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "5432:5432"   # host:container

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    depends_on:
      pgvector:
        condition: service_healthy
    volumes:
      - pgadmindata:/var/lib/pgadmin

#  poppano-gpt:
#    image: poppano-gpt
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://pgvector:5432/ai
#      SPRING_DATASOURCE_USERNAME: ai
#      SPRING_DATASOURCE_PASSWORD: ai
#      SPRING_AI_OLLAMA_BASE_URL: http://host.docker.internal:11434
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    ports:
#      - "8080:8080"
#    depends_on:
#      pgvector:
#        condition: service_healthy
#      pgadmin:
#        condition: service_started
#
#  poppano-gpt-native:
#    image: poppano-gpt-native
#    environment:
#      SERVER_PORT: 8081
#      SPRING_DATASOURCE_URL: jdbc:postgresql://pgvector:5432/ai
#      SPRING_DATASOURCE_USERNAME: ai
#      SPRING_DATASOURCE_PASSWORD: ai
#      SPRING_AI_OLLAMA_BASE_URL: http://host.docker.internal:11434
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    ports:
#      - "8081:8081"
#    depends_on:
#      pgvector:
#        condition: service_healthy
#      pgadmin:
#        condition: service_started

volumes:
  pgdata:
  pgadmindata:
